// disini kita membuat model untuk artikel dan isi artikle nya

class artikel {
  final String artikel_title;
  final String artikel_text;
  final String artikel_imageurls;

  const artikel(
      {required this.artikel_title,
      required this.artikel_text,
      required this.artikel_imageurls});
}

const artikelList = [
  artikel(
    artikel_title: 'Kenali 5 Penyebab Susah Bab Karena Diet',
    artikel_text:
        'Susah BAB saat diet sering terjadi ketika menjalani program penurunan berat badan yang'
        'kurang tepat. Untuk mencegah hal tersebut terjadi, ada beberapa hal yang perlu'
        'diperhatikan agar Anda bisa mendapatkan berat badan ideal tanpa sembelit.'
        'Susah BAB atau sembelit merupakan kondisi ketika frekuensi BAB kurang dari 3 kali dalam'
        'seminggu. Pada penderita sembelit, tinja menjadi kering dan keras sehingga sulit dikeluarkan.'
        'Sembelit berkaitan erat dengan pola makan. Pembatasan nutrisi tertentu, seperti yang dilakukan'
        'oleh orang yang sedang berdiet, dapat menyebabkan susah BAB.'
        'Penyebab Susah BAB saat Diet'
        'Berikut adalah beberapa penyebab susah BAB saat diet:'
        '1. Kurang asupan serat'
        'Kekurangan asupan serat merupakan penyebab utama susah BAB saat diet. Serat terdiri'
        'dari 2 jenis, yakni serat larut dan tidak larut. Keduanya penting untuk melancarkan'
        'pencernaan dengan cara yang sedikit berbeda.Serat larut menyerap air dan membentuk zat'
        'seperti gel agar tinja menjadi lebih lembek sehingga dapat melewati usus dengan lancar.'
        'Sementara itu, serat tidak larut memadatkan dan mendorong tinja agar tetap bergerak.Serat'
        'tidak hanya terdapat dalam buah-buahan dan sayuran, tetapi juga ada dalam biji-bijian,'
        'kacang-kacangan, dan polong-polongan.'
        '2. Adaptasi ketika asupan karbohidrat berkurang'
        'Pada umumnya, diet dilakukan dengan membatasi karbohidrat. Padahal karbohidrat'
        'merupakan sumber energi yang utama. Ketika asupan karbohidrat berkurang, tubuh akan'
        'mengambil energi dengan membakar cadangan lemak di tubuh. Memangkas karbohidratsecara drastis dalam waktu singkat dapat membuat sistem pencernaan ‘kaget’. Tubuh'
        'memerlukan waktu untuk menyesuaikan diri yang berakibat susah BAB saat diet.'
        '3. Kelebihan asupan lemak'
        'Selain memangkas karbohidrat, biasanya diet juga dilakukan dengan membatasi asupan'
        'lemak. Namun dalam diet keto, pola makan yang disarankan adalah mengonsumsi'
        'makanan rendah karbohidrat dan tinggi lemak. Gorengan, daging, makanan cepat saji, atau'
        'makanan berlemak tinggi lainnya dapat memperlambat pencernaan, sehingga'
        'menyebabkan susah BAB saat diet. Kendati demikian, bukan berarti Anda harus'
        'menghindari lemak sepenuhnya. Agar BAB tetap lancar, dianjurkan untuk mengonsumsi'
        'makanan yang mengandung lemak baik dalam jumlah wajar, seperti alpukat, biji-bijian,'
        'dan kacang-kacangan.'
        '4. Kekurangan cairan'
        'Saat tubuh kekurangan cairan, usus akan menyerap air dari tinja, sehingga tinja menjadi'
        'kering dan keras. Oleh karena itu, di samping memerhatikan asupan makanan saat diet,'
        'jangan lupa untuk mencukupi kebutuhan cairan. Minumlah paling tidak 8 gelas air setiap'
        'harinya. Agar berat badan ideal, Anda juga sebaiknya menghindari minuman manis yang'
        'dapat menyumbang tambahan asupan kalori.'
        '5. Kurang olahraga'
        'Banyak orang yang menjalani diet lebih memerhatikan asupan makanan tanpa rutin'
        'berolahraga. Padahal, selain dapat membakar kalori, olahraga dapat mengatasi susah BAB'
        'saat diet. Olahraga dapat menurunkan durasi yang dibutuhkan makanan untuk bergerak'
        'melewati usus besar. Hal ini membuat jumlah air yang diserap usus dari tinja berkurang,'
        'sehingga tinja tidak menjadi kering dan keras. Selain itu, olahraga dapat meningkatkan'
        'frekuensi pernapasan dan detak jantung. Keduanya dapat membantu merangsang kontraksi'
        'alami otot-otot usus agar lebih lancar dalam mengeluarkan tinja. Itulah beberapa hal yang'
        'dapat menyebabkan susah BAB saat diet. Jika BAB Anda tidak lancar saat menjalani pola'
        'diet tertentu, disarankan untuk mengevaluasi pola diet Anda. Diet yang sehat seharusnya'
        'membuat Anda dapat meraih berat badan impian tanpa efek samping. Jika Anda telah'
        'memperbanyak serat, mengonsumsi lemak sehat, mencukupi cairan, serta rutin'
        'berolahraga, namun masih mengalami susah BAB saat diet, sebaiknya Anda berkonsultasi'
        'dengan dokter untuk mendapatkan solusi yang tepat dan efektif.',
    artikel_imageurls:
        "https://res.cloudinary.com/dk0z4ums3/image/upload/v1589880171/attached_image/ketahui-perbedaan-nyeri-perut-bawah-dan-atas-beserta-pengobatannya-0-alodokter.jpg",
  ),
  artikel(
      artikel_title: 'CARA TERBAIK MELINDUNGI DIRI DARI BAHAYA OMICRON',
      artikel_text:
          'Bahaya Omicron diduga akibat tingkat penularannya yang tinggi, walaupun tingkat'
          'keparahan penyakitnya relatif lebih rendah. Hal ini terbukti dengan penyebarannya'
          'yang cepat di seluruh dunia, termasuk di Indonesia. Lantas, apa saja yang harus'
          'diwaspadai dan bagaimana cara kita melindungi diri?'
          'Di Indonesia, kasus COVID-19 varian Omicron sebagian besar datang dari pelaku'
          'perjalanan luar negeri dan warga negara asing. Oleh karena itu, pemerintah mengimbau'
          'masyarakat untuk menahan diri agar tidak bepergian ke negara-negara dengan bahaya'
          'Omicron yang tinggi. Selain datang dari orang-orang yang baru saja melakukan perjalanan luar negeri, COVID-'
          '19 varian Omicron ini juga sudah menjadi transmisi lokal di Indonesia. Hal ini berarti'
          'kewaspadaan dan kedisiplinan dalam menerapkan protokol kesehatan tetaplah menjadi'
          'sebuah keharusan, guna melindungi diri serta keluarga.'
          'Apakah COVID-19 Varian Omicron Lebih Berbahaya?'
          'Badan kesehatan dunia (WHO) memprediksi bahwa kasus COVID-19 varian Omicron'
          'akan mengalami peningkatan yang lebih tinggi daripada varian Delta. Tingkat penularan'
          'yang tinggi ini membuat Omicron dapat menginfeksi orang yang sudah divaksin COVID-'
          '19 dan bahkan tidak menimbulkan gejala.'
          'Meski demikian, bahaya Omicron tersebut diiringi dengan tingkat keterisian rumah sakit'
          'yang lebih rendah. Uji klinis menunjukkan bahwa risiko terjadinya COVID-19 dengan'
          'gejala parah lebih rendah pada pasien yang terinfeksi Omicron dibandingkan varian'
          'Delta. Namun, hal ini masih memerlukan penelitian lebih lanjut.Selain tingkat penularan dan keparahan penyakit, hal-hal seputar bahaya Omicron yang'
          'juga banyak menimbulkan pertanyaan adalah gejala umum dari penyakit ini. Sejumlah'
          'studi menungkapkan bahwa gejala COVID-19 varian Omicron tidak jauh berbeda dengan'
          'gejala COVID-19 pada umumnya.'
          'Gejala pada setiap orang juga bisa berbeda, tergantung pada beberapa faktor, mulai dari'
          'status vaksinasi, usia, dan ada tidaknya kondisi medis tertentu. Menurut penelitian,'
          'berikut ini adalah beberapa gejala yang umum ditemukan pada pasien COVID-19 varian'
          'Omicron:'
          ' Pilek'
          ' Sakit kepala'
          ' Kelelahan'
          ' Bersin-bersin'
          ' Sakit tenggorokan'
          ' Hidung tersumbat'
          ' Menggigil'
          ' Demam'
          'Meski tingkat keparahan penyakit pada COVID-19 varian Omicron ini diduga lebih'
          'rendah daripada varian lainnya. Namun, orang yang belum mendapatkan vaksin COVID-'
          '19 tetap berisiko tinggi mengalami panyakit parah. Oleh karena itu, pastikan Anda'
          'melakukan vaksinasi COVID-19 untuk mengurangi risiko terinfeksi Omicron.'
          'Apa yang Perlu Diwaspadai dari Bahaya Omicron?'
          'COVID-19 varian Omicron menimbulkan banyak kekhawatiran. Terlebih, aktivitas'
          'sehari-hari mulai kembali seperti sebelumnya, termasuk bekerja di kantor, rekreasi, dan'
          'kegiatan belajar-mengajar.'
          'Tingginya risiko penularan diduga merupakan salah satu bahaya Omicron yang harus'
          'diwaspadai. Oleh karena itu, pastikan Anda sudah mendapatkan vaksinasi COVID-19'
          'lengkap dan menjalankan protokol kesehatan di mana pun Anda berada untuk melindungi'
          'diri dari risiko tertular.'
          'Sebagai salah satu upaya pencegahan, pemilihan dan cara mengenakan masker yang'
          'benar dapat melindungi Anda dari bahaya Omicron.'
          'Saat mengenakan masker, bagian hidung dan mulut harus tertutup, sehingga cairan atau'
          'aerosol tidak mudah masuk. Masker juga harus selalu dipakai saat berada di tempat'
          'umum, baik di dalam maupun di luar ruangan.Selain itu, jangan lupa untuk selalu menjaga jarak minimal 1 meter dengan orang lain,'
          'membuka ventilasi saat berada dalam ruangan, mencuci tangan secara rutin, serta'
          'menjauhi kerumunan.'
          'Asupan Nutrisi yang Tepat'
          'Agar tetap sehat dan terhindar dari bahaya Omicron, tubuh memerlukan asupan nutrisi'
          'yang tepat. Konsumsilah makanan yang beragam dengan porsi buah dan sayur lebih'
          'banyak. Anda juga dapat menambahkan kacang-kacangan dan lemak sehat, seperti'
          'minyak zaitun, wijen, atau kacang tanah.'
          'Konsumsi empon-empon, seperti kunyit dan jahe, juga dapat membantu menjaga'
          'kesehatan tubuh selama pandemi COVID-19.'
          'Kunyit sendiri diketahui dapat meredakan demam, batuk, sakit tenggorokan, dan sesak'
          'napas yang merupakan gejala awal infeksi COVID-19, serta meningkatkan daya tahan'
          'tubuh. Sementara itu, jahe dapat membantu melawan bakteri dan virus dalam tubuh,'
          'termasuk virus penyebab sakit tenggorokan.'
          'Meski bahaya Omicron masih memerlukan penelitian lebih lanjut untuk memastikan'
          'tingkat penularan dan keparahan penyakitnya, Anda tidak boleh lengah. Tetap terapkan'
          'protokol kesehatan dan lengkapi dosis vaksinasi Anda untuk melindungi diri dan'
          'keluarga dari COVID-19.'
          'Jika merasakan gejala COVID-19 varian Omicron seperti yang telah disebutkan di atas,'
          'konsultasikanlah dengan dokter untuk memastikannya dan mendapatkan penanganan'
          'yang sesuai',
      artikel_imageurls:
          'https://img.okezone.com/content/2021/10/21/620/2489299/peneliti-yakin-ada-orang-yang-kebal-covid-19-SWjASv5nFf.jpg'),
  artikel(
      artikel_title: 'Hati Hati, Berat Badan Turun Drastis Justru Berbahaya',
      artikel_text:
          'Berat badan turun drastis berbahaya bagi kesehatan. Jika Anda ingin memiliki'
          'bentuk tubuh ideal dengan menurunkan berat badan, cara terbaik adalah dengan'
          'melakukannya secara perlahan dan konsisten.'
          'Mereka yang punya masalah dengan bobot tubuh berlebih atau terobsesi untuk kurus,'
          'terkadang rela melakukan diet super ketat untuk menurunkan berat badan dengan cepat.'
          'Padahal, berat badan turun drastis bukan berarti lemak di dalam tubuh banyak berkurang'
          'Lemak sulit dibakar dalam waktu singkat. Ketika berat badan turun drastis, justru yang'
          'banyak hilang dari tubuh adalah air atau bahkan jaringan tubuh, bukan lemak. Diet terlalu'
          'ketat pun bisa membuat tubuh kelaparan dan tidak mendapatkan asupan nutrisi penting.'
          'Efek Samping Berat Badan Turun Drastis'
          ' Berat badan turun drastis sering kali dikaitkan dengan berbagai masalah kesehatan. Bobot'
          '  tubuh yang berkurang lebih dari 1 kg per minggu dapat menyebabkan berbagai kondisi'
          ' berikut:'
          ' Kelelahan'
          ' Hilangnya massa otot'
          ' Dehidrasi'
          ' Gangguan elektrolit'
          ' Gangguan metabolisme tubuh'
          ' Kekurangan gizi (malnutrisi)'
          ' Daya tahan tubuh berkurang'
          ' Tulang rapuh Rambut rontok'
          ' Menstruasi tidak teratur'
          ' Sembelit atau susah buang air besar'
          ' Pusing dan sakit kepala'
          ' Penyakit batu empedu'
          'Seperti Apa Penurunan Berat Badan yang Aman?'
          ' Penurunan berat badan yang aman adalah sekitar 0,5 kg hingga 1 kg per minggu. Angka'
          'tersebut memang dirasa tidak banyak, tapi berat badan yang turun setidaknya akan stabil'
          'setiap minggunya.'
          ' Untuk menurunkan berat badan sebanyak 0,5–1 kg per minggu, banyak ahli yang'
          'menyarankan untuk memangkas 500–1.000 kalori dalam asupan makanan harian Anda.'
          'Caranya yaitu dengan:'
          '  Mengurangi porsi makan dan makanlah secara perlahan'
          '  Memperbanyak konsumsi sayuran, buah, dan makanan berserat'
          '  Memperbanyak asupan makanan berprotein'
          '  Rutin berolahraga selama sekitar 30 menit per hari'
          '  Menghindari dan mengurangi camilan serta makanan manis'
          '  Tidak melewatkan sarapan'
          '  Mengonsumsi air sebanyak 2.350–2.500 mililiter per hari'
          '  Mengurangi asupan lemak dan cermat dalam mengonsumsi lemak sehat'
          'Diet yang sehat bisa berbeda pada tiap orang, tergantung pada kondisi medis, jenis'
          'kelamin, usia, dan aktivitas yang dijalani sehari-hari. Oleh karena itu, daripada mencoba'
          'diet ekstrim yang berisiko agar berat badan turun drastis atau cepat, lebih baik'
          'konsultasikan ke dokter untuk mendapatkan rencana diet yang sehat.'
          'Konsultasikan juga dengan dokter apabila Anda tidak sedang diet, tapi berat badan turun'
          ' drastis. Bisa jadi ada masalah kesehatan lain yang Anda alami, seperti penyakit tiroid,'
          'malnutrisi, kanker, diabetes, gangguan jantung, kerusakan organ hati dan ginjal, TB,'
          ' HIV, gangguan pencernaan, stres berat, atau depresi.',
      artikel_imageurls:
          'https://cms-cdnassets.sehatq.com/fit-in/1080x0/filters:quality(90)/public/img/article_img/macam-macam-timbangan-dan-tips-mengukur-berat-badan-yang-tepat-1592810179.jpg'),
  artikel(
      artikel_title: 'Inilah Penyebab Rambut Rontok Berlebihan',
      artikel_text:
          'Kehilangan berhelai-helai rambut setiap hari adalah hal yang normal. Tapi Anda'
          ' perlu waspada jika rambut rontok lebih dari 100 helai per hari. Dengan mengenali'
          ' penyebab rambut rontok berlebihan dan cara mencegahnya, Anda bisa terhindar'
          'dari risiko kesehatan yang berbahaya.'
          ' Rambut rontok sebanyak 50 hingga 100 helai setiap hari masih dianggap hal yang wajar.'
          'Hal tersebut seharusnya tidak akan menimbulkan masalah atau membuat kepala menjadi'
          'cepat botak. Alasannya karena rambut baru akan tumbuh dan menggantikan rambut'
          'rontok tersebut. Namun jika rambut rontok berlebihan, apalagi bila disertai dengan pertumbuhan rambut'
          'yang terganggu atau terhenti, kepala bisa kehilangan mahkota indahnya, baik untuk'
          'sementara maupun selamanya.'
          'Penyebab Rambut Rontok Berlebihan'
          'Rambut rontok berlebihan (lebih dari 100 helai per hari) secara medis disebut sebagai'
          'telogen effluvium. Kerontokan ini terjadi secara menyeluruh pada bagian kepala sehingga'
          'tidak menyebabkan kebotakan pada satu area saja (pitak).'
          'Akibatnya, rambut tampak tipis secara keseluruhan. Kondisi ini bisa terjadi setelah tubuh'
          'mengalami stres atau tertekan, baik secara fisik maupun emosional.'
          'Secara umum, rambut rontok berlebihan dan pertumbuhan rambut yang lambat, bisa'
          'disebabkan oleh faktor-faktor berikut: Stres secara emosional, misalnya kehilangan pekerjaan, sedang menjalani proses'
          'perceraian, keluarga sakit parah, dan sebagainya'
          ' Stres fisik yang intensif, seperti melahirkan atau beban pekerjaan yang tinggi'
          ' Adanya perubahan hormonal, seperti yang terjadi pada wanita hamil atau setelah melahirkan dan saat menyusui'
          ' Kekurangan gizi, seperti protein dan zat besi, misalnya pada penderita gangguan makan'
          ' Menderita penyakit tertentu, seperti infeksi berat, alopecia areata, penyakit'
          'kelenjar tiroid, infeksi jamur di kepala, penyakit autoimun, dan sifilis'
          ' Efek samping obat-obatan, seperti pemakaian pil KB, vitamin A dosis tinggi, obat'
          'antidepresan, dan obat hormonal'
          ' Mengalami demam tinggi, anemia parah, atau baru sembuh dari sakit'
          '  Berat badan turun 9 kg atau lebih'
          '  Baru sembuh dari sakit.'
          ' Menjalani pengobatan tertentu, seperti kemoterapi atau terapi radiasi.'
          ' Penggunaan produk perawatan rambut berbahan keras, seperti cat rambut,'
          'bleaching rambut, atau kebiasaan menggunakan pemanas rambut.'
          ' Rambut rontok berlebihan atau telogen effluvium bisa terjadi pada pria maupun wanita'
          ' dari segala usia. Namun, wanita lebih sering mengalami hal ini, terutama jika ada'
          ' perubahan hormonal.'
          'Rambut rontok berlebihan biasanya mulai terjadi antara 1–2 bulan setelah stres atau'
          'kondisi medis tertentu menimpa Anda.'
          ' Mengatasi Penyebab Rambut Rontok Berlebihan'
          'Dalam beberapa kasus, rambut rontok berlebihan tidak membutuhkan pengobatan'
          'khusus.Rambut Anda bisa tumbuh dan tebal kembali dalam beberapa bulan, terutama'
          ' jika akar masalah atau penyebab rambut rontok berlebihan sudah teratasi.'
          'Namun, beberapa kasus rambut rontok berlebihan mungkin memerlukan perawatan.'
          'Untuk mendapatkan perawatan yang tepat, Anda bisa berkonsultasi ke dokter kulit.'
          'Jika kerontokan rambut dianggap sudah dalam tahap memerlukan perawatan khusus,'
          'maka dokter akan merekomendasikan obat-obatan, pengangkatan sebagian kulit kepala,'
          'terapi laser untuk menumbuhkan rambut, atau mungkin operasi transplantasi rambut.Mencegah Rambut Rontok Berlebihan'
          'Agar rambut rontok berlebihan tidak semakin parah, Anda bisa melakukan langkah'
          'pencegahan. Salah satunya dengan membatasi penataan rambut menggunakan alat'
          ' pemanas dan bahan kimia, seperti mencatok, mengeriting rambut, atau mewarnai rambut.'
          'Jangan lupa untuk selalu mengaplikasikan kondisioner setelah keramas untuk melindungi'
          'helai rambut. Selain itu, hindari mengepang atau mengikat rambut, serta menyisir rambut dalam keadaan basah.'
          'Yuk, jaga kesehatan rambut dan tubuh mulai dari sekarang agar penyebab rambut rontok'
          'berlebihan tidak terjadi pada diri Anda',
      artikel_imageurls:
          'https://res.cloudinary.com/dk0z4ums3/image/upload/v1590643817/attached_image/inilah-penyebab-rambut-rontok-berlebih-0-alodokter.jpg'),
  artikel(
      artikel_title: 'Seperti Ini Ciri-Ciri Penyakit Mag Yang Perlu Diketahui',
      artikel_text:
          'Ada beragam ciri-ciri penyakit maag yang penting untuk Anda ketahui. Dengan'
          'mengetahui ciri-ciri penyakit maag, Anda bisa menghindari dan meminimalkan'
          'terjadinya komplikasi atau hal-hal yang mungkin membahayakan kesehatan akibat penyakit maag.'
          ' Nyeri ulu hati, mual, dan muntah setelah makan, erat dikaitkan dengan penyakit maag,'
          ' atau yang secara medis dikenal sebagai sindrom dispepsia. Kondisi ini bisa dialami oleh'
          ' siapapun, tak terkecuali ibu hamil. Namun, gejala atau ciri-ciri penyakit maag tidak'
          ' hanya itu saja. Masih ada beberapa gejala atau ciri-ciri penyakit maag lainnya yang perlu'
          ' diketahui agar penyakit maag yang Anda alami dapat dikenali dan segera diatasi Mengenali Ciri-Ciri Penyakit Maag'
          ' Sakit maag bisa dialami oleh siapa saja. Penyakit ini bisa disebabkan oleh berbagai hal,'
          ' mulai dari luka terbuka di lapisan dalam lambung (tukak lambung), infeksi bakteri'
          'Helicobacter pylori, hingga efek samping penggunaan obat antiinflamasi nonsteroid (OAINS).'
          ' Seseorang yang menderita penyakit maag biasanya akan mengalami gejala atau ciri-ciri penyakit maag yang meliputi:'
          '  Nyeri ulu hati disertai sensasi terbakar di bagian dada'
          ' Mual saat atau setelah makan'
          ' Perut kembung dan terasa penuh'
          ' Mudah kenyang'
          ' Sering sendawa'
          ' Intoleransi terhadap makanan berlemak'
          ' Nafsu makan menurun karena perut terasa sakit Naiknya asam lambung'
          ' Penurunan berat badan'
          'Selain itu, ada pula gejala atau ciri-ciri penyakit maag yang terbilang berbahaya dan perlu segera diatasi:'
          ' Mual dan muntah secara terus menerus'
          ' Tinja berwarna gelap dan cair'
          ' Nyeri perut yang tiba-tiba dan terasa begitu menyakitkan'
          ' Muntah darah'
          ' Sulit bernapas'
          ' Anemia'
          'Cara Mencegah Penyakit Maag'
          'Sebelum mengalami penyakit maag, ada baiknya Anda melakukan pencegahan penyakit'
          ' maag sedini mungkin. Ini bisa dilakukan dengan mengubah pola hidup, termasuk:'
          'Menghindari konsumsi makanan tertentu'
          'Ada beberapa makanan yang bisa memicu sakit maag, seperti makanan tinggi lemak,'
          'makanan pedas, dan makanan asam. Kurangi atau jika memungkinkan hindarilah'
          'makanan-makanan tersebut guna mencegah timbulnya penyakit maag.'
          'Menghindari konsumsi minuman tertentu'
          'Untuk mencegah penyakit maag, selain menghindari konsumsi makanan penyebab sakit'
          'maag, Anda juga dianjurkan untuk menghindari konsumsi minuman bersoda, minuman'
          'berkafein seperti kopi dan teh, serta minuman beralkohol. Pasalnya, minuman tersebut'
          'berisiko menyebabkan iritasi lambung'
          'Berhenti merokok'
          'Perokok diketahui lebih berisiko terkena sakit maag dibandingkan mereka yang tidak'
          'merokok sebab senyawa yang terkandung dalam rokok bisa menghambat tubuh Anda'
          'memproduksi zat yang berperan untuk melindungi diri dari asam lambung.'
          'Jika Anda mengami ciri-ciri penyakit maag, segera periksakan diri ke dokter. Dokter'
          'akan menanyakan riwayat keluhan Anda, dilanjutkan dengan pemeriksaan fisik dan'
          'pemeriksaan penunjang seperti endoskopi, untuk mengetahui tingkat keparahan maag'
          'yang diderita. Selain itu, dokter mungkin akan menganjurkan untuk menjalani rawat inap'
          'di rumah sakit apabila ditemukan tanda-tanda yang berbahaya.',
      artikel_imageurls:
          'https://img.antaranews.com/cache/800x533/2019/09/18/PicsArt_09-18-08.27.34.jpg.webp'),
  artikel(
      artikel_title: '4 Cara Meninggikan Badan Yang Sehat Dan Alami',
      artikel_text:
          'Ada beragam cara meninggikan badan yang dapat dengan mudah Anda lakukan,'
          'mulai dari menjaga pola makan hingga mencukupi kebutuhan tidur. Bila Anda'
          'ingin menambah tinggi badan, simak penjelasan tentang cara meninggikan badan yang sehat dan alami.'
          'Tinggi badan seseorang ditentukan oleh banyak faktor, seperti jenis kelamin, asupan'
          'nutrisi, pola tumbuh kembang, dan kondisi kesehatan secara keseluruhan. Namun, faktor'
          'genetik atau keturunan memegang peran paling besar dalam pertumbuhan dan tinggi maksimal seseorang.'
          ' Hingga saat ini, masih belum ada cara yang terbukti efektif meninggikan badan setelah'
          ' melewati masa pertumbuhan. Umumnya, tubuh tidak meninggi lagi setelah usia 21 tahun.'
          'Namun, ada beberapa perubahan pola hidup bisa Anda terapkan untuk membantu postur tubuh tampak lebih tinggi.'
          ' Beragam Cara Meninggikan Badan yang Sehat dan Alami'
          'Berikut ini adalah berbagai cara meninggikan badan yang bisa Anda coba terapkan dengan mudah:'
          '1. Memperbaiki postur tubuh'
          'Postur tubuh dapat memengaruhi tinggi badan seseorang. Misalnya, kebiasaan'
          'membungkuk saat duduk bisa membuat tulang belakang bergeser dan menyesuaikan'
          'dengan postur tubuh. Kebiasaan ini cenderung membuat tubuh lebih pendek dari yang'
          'seharusnya.Selain itu, menjaga postur tubuh yang baik juga dapat memberikan banyak manfaat'
          'kesehatan, termasuk menjaga fleksibilitas dan keseimbangan tubuh, memelihara'
          'kesehatan sendi, membantu pernapasan, serta mencegah sakit punggung, bahu, dan leher.'
          ' Oleh karena itu, selalu tegakkan punggung dan tarik pundak ke belakang, baik saat duduk'
          'maupun berdiri. Jika Anda memiliki masalah dengan postur tubuh, Anda bisa melakukan'
          'latihan khusus untuk memperbaiki postur tubuh sesuai kondisi dan kebutuhan Anda,misalnya dengan olahraga pilates.'
          '2. Memperbaiki pola makan'
          'Selain lauk pauk, pola makan yang sehat dan bergizi haruslah mencakup buah-buahan,'
          'sayuran, atau biji-bijian utuh. Selain itu, penting juga untuk membatasi atau menghindari'
          'makanan yang mengandung tinggi gula atau lemak trans.'
          'Pola makan sehat yang kaya akan vitamin dan mineral juga penting sebagai salah satu'
          'cara meninggikan badan dan menjaga kesehatan tulang. Beragam nutrisi yang penting'
          'untuk kesehatan tulang meliputi kalsium, vitamin D, dan protein.'
          'Anda bisa mendapatkan sumber protein, kalsium dan vitamin D yang baik dari berbagai'
          'jenis makanan, seperti telur, ayam, daging tanpa lemak, ikan sarden, dan ikan tuna.'
          ' Apabila dikonsumsi sejak dini, nutrisi tersebut bisa mencegah tinggi badan yang berkurang pada masa lansia akibat osteoporosis.'
          '3. Mencukupi kebutuhan istirahat dan tidur'
          'Meski tidak memengaruhi tinggi badan dalam jangka panjang, pola tidur yang teratur'
          'sangat penting karena berpengaruh pada kesehatan tubuh secara keseluruhan, termasuk mendukung proses tumbuh kembang secara optimal.'
          'Pola tidur yang disarankan bagi orang dewasa adalah 7–9 jam setiap harinya, sedangkan'
          'untuk remaja usia 14–17 tahun adalah 8–10 jam per hari.'
          '4. Berolahraga secara teratur'
          ' Olahraga secara teratur minimal 30 menit setiap hari memiliki banyak manfaat bagi'
          ' kesehatan, termasuk memperkuat otot dan tulang. Ada beberapa olahraga yang dianggap'
          'efektif sebagai cara meninggikan badan, yaitu:'
          ' Latihan kekuatan, seperti push-up dan sit-up'
          ' Latihan fleksibilitas, seperti yoga'
          ' Latihan aerobik, seperti lompat tali, berenang, dan bersepeda'
          'Lakukan langkah-langkah di atas sebagai cara meninggikan badan dengan sehat dan'
          'alami. Ingat, jangan mudah percaya dengan berbagai produk peninggi badan yangmenawarkan hasil instan dan banyak ditemukan di pasaran, misalnya dalam bentuk susu,'
          'suplemen, atau pil.'
          'Jika berbagai cara meninggikan badan di atas telah dilakukan, tetapi hasilnya tak kunjung'
          'Anda peroleh, konsultasikan ke dokter untuk mendapatkan saran yang tepat dan aman'
          'guna menambah tinggi badan',
      artikel_imageurls:
          'https://image-cdn.medkomtek.com/59V7zppzL9niVxtqCAnusYEIoFw=/640x360/smart/filters:quality(75):strip_icc():format(webp)/klikdokter-media-buckets/medias/2312819/original/011927700_1582786259-Peran-Susu-untuk-Menambah-Tinggi-Badan-shutterstock_1074888872.jpg'),
  artikel(
      artikel_title:
          'Penyebab Demam Setelah Vaksinasi Pada Anak Dan Cara Mengatasinya',
      artikel_text:
          'Setelah menjalani vaksinasi atau imunisasi, beberapa anak mungkin mengalami'
          'efek samping ringan, salah satunya berupa demam. Kondisi ini wajar terjadi. Anda'
          'dapat melakukan beragam cara untuk mengatasi ketidaknyamanan ketika anak demam setelah vaksinasi.'
          'Demam adalah meningkatnya suhu tubuh dari kondisi normal. Suhu tubuh normal pada'
          'anak-anak berkisar antara 36–37°C. Anak dikatakan demam jika suhu tubuhnya lebih dari'
          ' 37,2°C bila diukur di ketiak, lebih dari 37,8°C bila diukur di mulut, atau di atas 38°C biladiukur di dubur menggunakan termometer.'
          'Perlu diketahui, demam bukanlah penyakit. Demam merupakan gejala, bisa akibat infeksi'
          'virus, seperti yang umum dialami penderita COVID-19, infeksi bakteri, peradangan,'
          'ataupun reaksi pascavaksinasi.'
          'Penyebab Demam setelah Vaksinasi pada Anak'
          'Vaksinasi adalah proses pemberian vaksin dengan cara disuntikkan atau diteteskan ke'
          'dalam mulut untuk merangsang pembentukan antibodi terhadap penyakit tertentu.'
          'Demam menunjukkan tubuh anak merespons vaksin. Para ahli berpendapat, demam'
          'menandakan sistem imun bekerja dengan baik dalam mengenali dan mempelajari cara'
          'untuk melawan penyakit tersebut jika suatu waktu terinfeksi.Meski demikian, tingkat demam tergantung pada masing-masing anak dan tidak'
          'menunjukkan seberapa baik vaksin bekerja.'
          'Beberapa anak mungkin tidak menunjukkan reaksi apa pun, baik demam maupun gejala'
          'lainnya setelah vaksinasi. Kondisi ini juga normal dan vaksin tetap bekerja dalam'
          'meningkatkan produksi antibodi di dalam tubuh.'
          'Cara Mengatasi Demam setelah Vaksinasi pada Anak'
          'Saat demam, Si Kecil biasanya juga merasa lemas dan berkeringat. Hal ini karena demam'
          'membuat tubuh kehilangan cairan lebih banyak daripada biasanya. Semakin tinggi suhu'
          ' tubuh, semakin banyak pula cairan yang dibutuhkan tubuh.'
          'Oleh karena itu, pastikan kebutuhan cairan anak terpenuhi saat demam agar ia terhindar'
          'dari dehidrasi. Dehidrasi tidak hanya berarti tubuh kehilangan cairan, tetapi juga'
          'elektrolit, seperti garam dan kalium yang penting untuk beragam fungsi tubuh.'
          'Untuk mencegah dehidrasi, Anda bisa memberikan Si Kecil minuman elektrolit untuk'
          'mengganti mineral yang hilang dengan cepat. Sementara untuk mengatasi'
          'ketidaknyamanan akibat demam, Anda bisa melakukan cara-cara berikut:'
          '  Kenakan pakaian yang tipis dan menyerap keringat'
          ' Hindari memakaikan pakaian berlapis atau menutupi tubuhnya dengan selimuttebal, karena dapat memicu kenaikan suhu tubuh'
          '  Berikan kompres air hangat di kening'
          ' Jaga suhu kamar tidak terlalu panas dan tidak terlalu dingin'
          ' Demam juga dapat diredakan dengan obat pereda demam, seperti paracetamol atau'
          'ibuprofen. Namun, umumnya demam tidak perlu ditangani dengan pemberian obat,'
          ' terutama jika anak masih aktif dan mau makan atau minum.'
          ' Ingat, selalu konsultasikan terlebih dahulu dengan dokter sebelum memberikan obat apa'
          'pun kepada anak.Meskipun demam tidak selalu menandakan kondisi yang serius,'
          'waspadai jika Si Kecil mengalami peningkatkan suhu tubuh seperti berikut:'
          ' Suhu tubuh yang diukur melalui dubur mencapai 38°C atau lebih pada anak usiakurang dari 3 bulan'
          '  Suhu tubuh 39°C atau lebih pada semua usia anak'
          'Selain memantau suhu tubuhnya, segera periksakan anak ke dokter bila muncul gejalalain yang menyertai demam, seperti:'
          '  Menolak makan, minum, atau menyusu Demam tidak kunjung reda setelah 1 hari pada anak usia kurang dari 2 tahun, atau'
          '3 hari pada anak usia 2 tahun atau lebih'
          ' Sering demam, meski hanya berlangsung selama beberapa jam'
          ' Diare atau muntah berkepanjangan'
          ' Ruam kulit'
          ' Dehidrasi yang ditandai dengan jarang buang air kecil, tidak mengeluarkan air'
          'mata saat menangis, atau tampak lemas'
          'Anda juga harus segera mencari pertolongan medis bila demam pada anak disertai gejala'
          'yang lebih serius, seperti tidak berhenti menangis, sesak napas, kejang, ubun-ubun bayiterlihat cekung, dan penurunan kesadaran.'
          'Sikapi demam setelah vaksinasi dengan tenang. Namun, tetap pantau kondisi anak dan'
          'waspadai munculnya tanda dehidrasi atau kegawatdaruratan lainnya.',
      artikel_imageurls:
          'https://pict.sindonews.net/dyn/732/pena/news/2022/02/20/15/691483/survei-penerimaan-masyarakat-terhadap-vaksinasi-booster-dan-anak-meningkat-yjc.jpg'),
  artikel(
      artikel_title: ' Ketahui Cara Mengatasi Gangguan Kecemasan',
      artikel_text:
          'Bagi penderita gangguan kecemasan, pikiran negatif dan rasa gelisah sering kali'
          'sulit dihilangkan, bahkan sampai mengganggu aktivitas sehari-hari. Jika Anda'
          'mengalami hal tersebut, simak cara mengatasi gangguan kecemasan berikut ini.'
          'Rasa cemas yang muncul sesekali, terutama ketika menghadapi situasi yang membuat'
          ' stres atau khawatir, adalah hal yang normal dan dapat reda dengan sendirinya. Namun'
          'jika rasa cemas sering muncul tanpa sebab yang jelas, berlebihan, dan sulit diredam, bisa'
          'jadi itu disebabkan oleh gangguan kecemasan.Cara Mengatasi Gangguan Kecemasan'
          'Gangguan kecemasan ada bermacam-macam, mulai dari gangguan kecemasan'
          'menyeluruh, serangan panik, hingga fobia. Meskipun masing-masing gangguan'
          'kecemasan memiliki karakteristik yang berbeda, secara umum kondisi ini dapat ditanganidengan psikoterapi dan obat-obatan.'
          ' Salah satu bentuk psikoterapi yang paling dikenal adalah terapi perilaku kognitif (CBT),'
          'di mana penderita diarahkan ke cara berpikir, bereaksi, dan berperilaku yang dapat membantunya mengurangi gejala kecemasan.'
          ' Selain dengan obat-obatan dan psikoterapi, ada beberapa cara sederhana yang dapat'
          'dilakukan secara mandiri dan telah terbukti dapat membantu mengurangi gejala gangguan kecemasan, yaitu:1. Menarik napas yang dalam'
          'Bernapas dengan dalam dapat membuat tubuh relaks dan mengurangi aktivitas saraf di'
          'otak yang menyebabkan rasa cemas. Ketika mengalami kecemasan, tarik napas panjang'
          'selama lima detik, kemudian tahan selama lima detik, lalu lepaskan kembali perlahanlahan dalam lima detik juga. Lakukanlah beberapa kali sampai pikiran lebih tenang.'
          '2. Memusatkan pikiran pada aktivitas yang dijalani'
          'Ketika merasa cemas, fokus Anda akan terganggu. Jika ini terjadi, cobalah untuk kembali'
          'fokus pada hal yang akan Anda lakukan. Misalnya, jika ada jadwal membersihkan rumah'
          'atau mencuci baju, lakukanlah. Jika ada jadwal berkumpul dengan teman-teman, tetaplah'
          'pergi. Duduk diam tanpa melakukan apa pun dan diliputi kekhawatiran tentang hal-hal'
          'yang mungkin terjadi justru akan memperburuk kecemasan.'
          '3. Menerapkan metode 3-3-3'
          'Lihatlah ke lingkungan sekitar dan sebut tiga benda. Kemudian sebutkan tiga suara yang'
          'mungkin sedang terdengar saat itu. Lanjutkan dengan menyebut tiga bagian tubuh, seperti'
          'jari, lengan, dan pergelangan kaki, sambil menggerak-gerakkannya dengan santai. Teknik'
          'ini dapat membantu menghentikan atau mengalihkan pikiran negatif yang membuat Anda gelisah.'
          '4. Menghindari kafein dan alkohol'
          'Alkohol dapat memberikan sensasi rileks sebagai efek jangka pendek. Namun jika'
          ' dikonsumsi terlalu sering atau berlebihan, alkohol justru dapat membuat gangguan cemas menjadi lebih berat.'
          'Konsumsi kafein, baik dalam bentuk kopi, cokelat, maupun teh, juga dapat memicu dan'
          'memperburuk gejala kecemasan. Beberapa studi menunjukkan bahwa konsumsi kopi dan'
          'teh dapat membuat seseorang merasa lebih gelisah dan sulit berkonsentrasi, terlebih jika'
          'dikonsumsi dalam jumlah berlebihan, yaitu lebih dari 2 gelas per hari.'
          ' 5. Bercerita kepada orang yang dipercaya'
          ' Curhat atau menceritakan apa yang sedang Anda rasakan dan alami kepada orang yang'
          'Anda percaya bisa meringankan kecemasan Anda. Orang tersebut bisa saja psikiater,'
          'teman dekat, atau anggota keluarga yang memahami kondisi Anda.'
          ' Sebagai alternatif, cobalah mencari support group yang beranggotakan orang-orang'
          'dengan keluhan yang serupa, sehingga bisa saling berbagi pengalaman dan tips tentang bagaimana cara mengatasi gangguan kecemasan.'
          ' 6. Menyediakan waktu untuk diri sendiri'
          'Sediakan waktu untuk berjalan santai, melakukan meditasi, mendapatkan pijatan, atau'
          'berendam di air hangat. Bila perlu, matikan telepon genggam Anda selama beberapa saat'
          'agar Anda tidak terganggu.Terkadang kecemasan dapat disebabkan oleh meningkatnya hormon stres. Cara-cara'
          'relaksasi tersebut bisa membuat Anda merasa lebih tenang, sehingga rasa cemas pun bisa reda.'
          '7. Makan teratur dan minum cukup air'
          'Ketika sibuk atau merasa cemas, seseorang dapat melupakan jadwal makannya. Padahal'
          'kadar gula darah yang rendah karena terlambat makan dapat menyebabkan seseorang'
          'lebih mudah emosi dan cemas. Kekurangan cairan atau dehidrasi juga dapat membuat'
          'jantung berdetak lebih cepat dan memperburuk rasa cemas.'
          'Efektivitas langkah-langkah di atas belum tentu sama pada setiap orang dengan gangguan'
          'kecemasan. Hal terpenting untuk meredakan kecemasan adalah mengenali pencetus rasa'
          'cemas tersebut, kemudian menentukan cara yang paling cocok bagi Anda untuk meredakannya.'
          ' Agar hasilnya optimal, Anda disarankan untuk berkonsultasi ke dokter guna mendapat'
          'penanganan lebih lanjut. Terlebih jika gangguan kecemasan sudah menimbulkan'
          'kesulitan dalam menjalani aktivitas, susah tidur, kelelahan, sulit berkonsentrasi, hingga'
          'gejala depresi berupa ide atau pikiran untuk bunuh diri.',
      artikel_imageurls:
          'https://akcdn.detik.net.id/visual/2019/07/19/013ba225-7397-4912-b7fd-2a6b64b33fe9_169.jpeg?w=650'),
  artikel(
      artikel_title:
          'Tanda tanda kurang darah yang jarang di ketahui dan disadari',
      artikel_text:
          'Sering merasa lelah dan pusing padahal tidak melakukan aktivitas fisik yang berat,'
          'bisa jadi merupakan tanda-tanda kurang darah atau anemia. Kondisi ini terjadi'
          'akibat tubuh tidak memiliki sel darah merah yang cukup untuk membawa oksigen ke seluruh tubuh.'
          'Ada beragam jenis amenia, di antaranya anemia defisiensi besi, anemia defisiensi'
          ' vitamin, anemia yang disebabkan oleh kehamilan, serta anemia aplastik. Namun, anemia'
          'yang paling sering diderita oleh sebagian orang adalah anemia defisiensi besi. Anemia defisiensi besi terjadi ketika tubuh kekurangan zat besi yang diperlukan dalam'
          'memproduksi sel darah merah. Namun, banyak orang yang masih belum menyadari'
          'bahwa dirinya mengalami kurang darah, bahkan ketika mengalami gejala-gejalakekurangan darah.'
          'Beragam Tanda Kurang Darah'
          'Penderita anemia defisiensi besi umumnya akan mengalami gejala kelelahan, pusing,'
          'sulit konsentrasi, sakit kepala, kesemutan, kulit terlihat pucat, tangan dan kaki dingin,'
          'nafsu makan berkurang, serta jantung berdebar-debar.'
          ' Selain itu, terdapat tanda-tanda kurang darah yang jarang diketahui secara umum, yaitu:'
          '1. Sering infeksiZat besi dibutuhkan dalam membangun dan menjaga sistem kekebalan tubuh secara'
          ' maksimal. Oleh karena itu, tak heran jika kekurangan asupan zat besi bisa membuat'
          'seseorang lebih rentan terserang infeksi.'
          '2. Rambut rontok'
          ' Saat tubuh kekurangan zat besi, pasokan oksigen ke kulit dan folikel rambut menjadi'
          ' berkurang, sehingga membuat kulit menjadi kering dan rusak.'
          'Kondisi ini bahkan bisa memicu rambut rontok secara berlebihan dan berhenti tumbuh.'
          'Namun, ketika asupan zat besi sudah tercukupi dan tubuh terbebas dari kurang darah,'
          'umumnya rambut dapat tumbuh kembali.'
          '3. Lidah bengkak'
          'Kurang darah dapat membuat organ-organ di seluruh tubuh mengalami kekurangan'
          ' oksigen, termasuk lidah. Kondisi ini dapat menyebabkan lidah menjadi bengkak,'
          'meradang, terlihat pucat, atau permukaannya tampak licin.'
          'Selain lidah yang bengkak, kurang darah juga dapat mengakibatkan mulut dan bibir'
          'menjadi kering, retak-retak, sariawan, dan terasa seperti terbakar.'
          '4. Sindrom restless leg'
          'Defisiensi zat besi juga dapat membuat penderitanya mengalami sindrom restless leg atau'
          'kaki gelisah. Pada sindrom ini, terdapat getaran yang menjalar di kaki, semacam aliran listrik.'
          'Hal ini membuat penderitanya memiliki dorongan untuk terus menggerakkan kaki seperti'
          'seseorang yang sedang gelisah.'
          '5. Kuku rapuh'
          'Kuku rapuh, retak, dan mudah patah, juga bisa menjadi tanda anemia akibat kekurangan'
          'zat besi. Jika semakin parah, bentuk kuku bisa menjadi seperti sendok, di mana ujung'
          'kuku naik atau terangkat sedangkan bagian tengah kuku datar. Namun, ini adalah gejala'
          'yang jarang terjadi.'
          'Agar Anda tidak mengalami kurang darah dan akhirnya menyebabkan terjadinya hal-hal'
          'di atas, penuhilah kebutuhan zat besi harian Anda. Salah satu caranya adalah dengan'
          'lebih mengutamakan asupan zat besi dari makanan sehari-hari.'
          'Untuk kurang darah atau anemia yang disebabkan oleh penyakit tertentu, kondisi tersebut'
          'perlu diperiksakan ke dokter agar dapat diobati sesuai penyebabnya',
      artikel_imageurls:
          'https://cdn-2.tstatic.net/tribunnews/foto/bank/images/ilustrasi-sakit-kepalajpg.jpg'),
  artikel(
      artikel_title: 'Bahaya Asam Lambung Jika Di Biarkan Terus Menerus',
      artikel_text:
          'Asam lambung merupakan salah satu zat yang berperan penting dalam proses'
          ' pencernaan. Namun jika kadarnya berlebihan atau terlalu sedikit, asam lambung'
          'bisa menimbulkan berbagai masalah kesehatan.'
          'Gangguan pencernaan, seperti nyeri perut, diare, dan kembung, merupakan beberapa'
          'masalah kesehatan yang dapat timbul akibat tidak normalnya kadar asam lambung. Jika'
          ' dibiarkan berlarut-larut tanpa penanganan, kondisi tersebut dapat menimbulkan penyakit'
          'serius yang berpotensi mengancam nyawa Apa Itu Asam Lambung?'
          'Sebelum mengetahui bahaya kadar asam lambung yang tak normal, Anda perlu tahu dulu'
          'bahwa asam lambung memiliki peran penting dalam proses pencernaan. Tanpa asam'
          'lambung atau jika kadarnya di lambung rendah, tubuh tidak dapat menyerap nutrisi dari makanan.'
          'Selain berperan dalam proses pencernaan, asam lambung juga berfungsi untuk'
          'menatralisir enzim dan membunuh kuman berbahaya yang mungkin ada di dalam makanan.'
          'Oleh karena itu, penting untuk memastikan kadar asam lambung sesuai kebutuhan tubuh.'
          'Jika jumlahnya berlebihan atau terlalu sedikit, dapat timbul beragam masalah kesehatan.Gangguan Kesehatan Jika Kekurangan Asam Lambung'
          ' Ketika tubuh tidak memproduksi cukup asam lambung, atau dalam istilah medis disebut'
          'hipokloridia, gejala yang mungkin akan muncul adalah:'
          ' Perut kembung'
          ' Sering bersendawa'
          '  Diare'
          ' Nyeri perut atau nyeri ulu hati'
          ' Mual dan muntah'
          ' Tubuh terasa lemas'
          ' Sering buang angin'
          'Selain itu, kurangnya asam lambung dalam jangka panjang juga dapat menimbulkan'
          'masalah gizi, seperti kekurangan vitamin, mineral, atau protein tertentu. Hal ini karena'
          'kurangnya asam lambung menyebabkan nutrisi-nutrisi tersebut tidak dapat dicerna'
          'dengan baik oleh tubuh.'
          'Gangguan Kesehatan Akibat Asam Lambung Berlebih'
          'Sebaliknya jika kadar asam lambung terlalu tinggi, ada beragam gangguan kesehatan'
          ' yang juga mungkin dapat terjadi, seperti:'
          '1. Nyeri ulu hati'
          'Heartburn atau nyeri ulu hati adalah sensasi perih di dada dan perut bagian atas, yang'
          'biasanya akan terasa lebih parah ketika berbaring atau membungkuk. Kondisi ini'
          'merupakan dampak dari asam lambung yang naik ke kerongkongan, dan bisa menandakan adanya tukak lambung.'
          'Jika keluhan nyeri ulu hati hanya terjadi sesekali, umumnya tidak diperlukan penanganan'
          'khusus. Namun, jika nyeri ulu hati sering terjadi, terasa berat dan menjalar hingga ke'
          'rahang, leher, atau lengan, diperlukan pemeriksaan dan pengobatan dari dokter.'
          '2. GERD atau penyakit asam lambung'
          'Gastroesophageal reflux disease atau GERD merupakan penyakit pencernaan kronis yang'
          'terjadi ketika asam lambung atau cairan dan isi lambung naik kembali ke kerongkongan,'
          'sehingga mengiritasi dinding kerongkongan.'
          'GERD ditandai dengan nyeri ulu hati yang muncul lebih dari dua kali dalam seminggu.'
          'Bahaya asam lambung yang satu ini bisa diobati dengan menjalani gaya hidup sehat,'
          'seperti menjauhi konsumsi kopi dan alkohol, berhenti merokok.Selain itu, Anda juga disaranan untuk mengonsumsi obat-obatan pereda asam lambung'
          'dan obat yang mempercepat pengosongan lambung (misalnya cisapride). Pada kasus'
          'tertentu, GERD perlu ditangani dengan operasi.'
          '3. Gigi rusak'
          'Asam lambung atau cairan lambung yang naik ke kerongkongan dan mulut dapat'
          'mengikis email gigi (lapisan terluar gigi). Akibatnya, gigi pun menjadi rusak. Tanpa'
          'pemeriksaan gigi rutin, biasanya orang tidak menyadari bahwa giginya rusak sampai'
          'kerusakaan yang terjadi sudah parah.'
          '4. Masalah pernapasan'
          'Asam lambung juga bisa memperparah penyakit asma atau pneumonia hingga'
          'menyebabkan sesak napas. Hal ini bisa terjadi bila asam lambung yang naik ke'
          'kerongkongan secara tidak sengaja masuk ke tenggorokan saat bernapas, dan masuk hingga ke paru-paru.'
          '5. Radang pada kerongkongan'
          'Asam lambung yang naik kembali ke kerongkongan (GERD) bisa menyebabkan iritasi'
          'pada dinding-dinding kerongkongan. Iritasi ini kemudian memicu terjadinya peradangan'
          'pada kerongkongan atau yang biasa disebut esofagitis.'
          '7. Esofagus Barrett'
          'Jika tidak diobati selama bertahun-tahun, asam lambung yang terus naik ke'
          'kerongkongan berpotensi menyebabkan esofagus Barret. Bahaya asam lambung yang'
          'satu ini merupakan komplikasi serius dari penyakit GERD.'
          'Pada esofagus Barrett, terjadi kerusakan jaringan kerongkongan yang menghubungkan'
          'mulut dengan lambung. Penyakit ini tidak memiliki gejala khusus, dan gejala yang'
          'muncul biasanya berhubungan atau mirip dengan GERD. Bahaya utama dari esofagus'
          'Barrett adalah terjadinya kanker esofagus.'
          'Untuk menjaga agar kadar asam lambung tetap seimbang, biasakan untuk makan dengan'
          'jadwal yang teratur. Selain itu, hindari makan terlalu cepat dan langsung berbaring'
          'setelah makan, agar asam lambung tidak naik.'
          'Jika keluhan gangguan pencernaan terkait asam lambung sering dirasakan atau gangguan'
          'asam lambung menyebabkan nyeri perut berat, warna feses hitam, muntah darah, atau'
          'sulit menelan, berkonsultasilah dengan dokter untuk mendapatkan pemeriksaan dan'
          'pengobatan yang sesuai.',
      artikel_imageurls:
          'https://asset.kompas.com/crops/n9JNqqCisrK5iuhVzLgpOJNVPRQ=/0x20:1000x520/780x390/data/photo/2020/04/28/5ea8333acd3b7.jpg'),
];
